### ISSUE TITLE
Interface to BIDS

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime-neuro-draft#7]
Implement basic functionality to load BIDS data into an sktime pandas. For a single experiment/patient, this would read into a single row, where each element in the row is a time series for a particular EEG channel

**Comment by SveaMeyer13** [comment]
I added my example pipeline for Interfacing with BIDS [here](https://github.com/sktime/sktime-neuro/blob/loading_bids_format/sktime/contrib/eeg_dev/Pipeline_Example.ipynb)
