### ISSUE TITLE
Implement a segmenter to create a classification problem

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime-neuro-draft#9]
transform a dataset loaded from BIDS (see https://github.com/sktime/sktime-neuro/issues/7) that converts from a single row problem to a multiple row problem based on an annotation provided to the segmenter

**Comment by SveaMeyer13** [comment]
I added an example of how this transformation could be done in the [example pipeline](https://github.com/sktime/sktime-neuro/blob/loading_bids_format/sktime/contrib/eeg_dev/Pipeline_Example.ipynb)
